# Generated by Django 5.2.3 on 2025-08-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="team", name="league",),
    ]
