# Generated by Django 5.2.3 on 2025-08-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_team_league"),
    ]

    operations = [
        migrations.RemoveField(model_name="match", name="user",),
    ]
