# Generated by Django 5.2.3 on 2025-08-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_match_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
